---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# docker-save-images-action
# Saves docker artifacts created by a workflow
# Saved docker artifacts can be used by subsequent jobs. for ex: deploy and test
name: "docker-save-artifacts"
# yamllint disable-line rule:line-length
description: "Save Docker Artifacts to be used later in the workflow"

inputs:
  docker-artifacts-to-save:
    description: "Space separated list of docker image names to be saved"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: 'Export Docker image(s) as tar'
      id: export_docker_images
      shell: bash
      run: |
        image_list="${{ inputs.docker-artifacts-to-save }}"
        if [ -z "$image_list" ]; then
          echo "Mandatory docker image names not provided"
          exit 1
        fi
        read -ra images <<< "$image_list"
        docker save "${images[@]}" -o docker-images.tar
        echo "docker-image-tar=docker-images.tar" >> $GITHUB_OUTPUT

    - name: 'Upload docker images tar artifact'
      # yamllint disable-line rule:line-length
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v4
      with:
        name: docker-image
        path: docker-images.tar
        if-no-files-found: error
        overwrite: true
        retention-days: 1
